import styles from '../styles/about.module.scss'
import profilePic from '../public/assets/profile.jpg'
import Image from 'next/image'
import Head from 'next/head'
import Button from '../components/button'
import Article from '../components/article'
import { info } from '../utils/personal'
import { BsLinkedin, BsFillPinMapFill, BsSuitHeartFill } from "react-icons/bs";


export default function About() {

    return (
        <>
            <Head>
                <title>About Francis Bernal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <section className={styles.container}>
                <h2 className={styles.title}>Discover all you need to know about me</h2>
                <div className={styles.column_container}>
                    <aside className={styles.aside_container}>
                        <figure className={styles.fig}>
                            <div className={styles.img_container}>
                                <Image
                                    className={styles.img_profile}
                                    src={profilePic}
                                    alt="a profile's photo of Francis."
                                    fill
                                    priority
                                />
                            </div>
                            <figcaption>Francisco Javier Bernal Cabra <br /> Junior Full-Stack Developer</figcaption>
                        </figure>
                        <ul className={styles.list_info}>
                            <li><BsSuitHeartFill className={`${styles.icon} ${styles.heart}`} /><span>27 años</span></li>
                            <li><BsFillPinMapFill className={`${styles.icon} ${styles.location}`} /><span>Málaga, España</span></li>
                            <li><BsLinkedin className={`${styles.icon} ${styles.linked}`} /><span>LinkedIn</span></li>
                        </ul>
                        <div className={styles.btn_container}>
                            <Button url="/contact" value="Contact" />
                            <Button url="https://google.es" value="Resume" />
                        </div>
                    </aside>
                    <div className={styles.article_container}>
                        {
                            info.map(item => {
                                return (
                                    <Article
                                        key={item.title}
                                        title={item.title}
                                        description={item.description}
                                        items={item.items}
                                    />
                                )
                            })
                        }
                    </div>
                </div>
            </section>
        </>
    )
}