import Head from 'next/head'
import Image from 'next/image'
import profilePic from '/public/assets/profile.jpg'
import styles from '@components/styles/Home.module.css'
import Button from '../components/button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Francis - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id={styles.section_container}>
        <div className={styles.img_container}>
          <Image
            className={styles.img_profile}
            src={profilePic}
            alt="a profile's photo of Francis."
            fill
            priority
            sizes="(max-width: 850px) 40vw,
                    (max-width: 410px) 50vw,
                      30vw"
          />
        </div>
        <h1>Hello, I'm Francis. Junior Full-Stack Developer</h1>
        <p>
          Hello, I’m Francis, a passionate web developer. I love creating websites and applications with javascript, using React and next as my favorite tools.
          I also master databases with mongodb and postgresql. I don’t separate from my linux terminal, where I use git and bash to manage my projects.
          I live in the beautiful city of Malaga, but I have no problem working with other time zones or languages, as I speak English quite well.
        </p>
        <div className={styles.btn_container}>
          <Button url="https://google.es" value="Resume" />
          <Button url="https://google.es" value="Contact" />
        </div>
      </section>
    </>
  )
}
