import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/projects.module.scss'
import Project from '../components/project'
import { projects } from '../utils/data'

export default function Projects() {
    const [filter, setFilter] = useState("all");    

    let data;

    if (filter === "all") {
        data = [...projects];
    }

    if (filter === "front") {
        data = projects.filter(project => project.type === "front");
    }

    if (filter === "back") {
        data = projects.filter(project => project.type === "back");
    }


    return (
        <>
            <Head>
                <title>Francis - Projects</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <section className={styles.container}>
                <h2>Check out my latest projects</h2>
                <div className={styles.filter_container}>
                    <button className={styles.filter_btn} onClick={() => setFilter("all")}>All</button>
                    <button className={styles.filter_btn} onClick={() => setFilter("front")}>Front-end</button>
                    <button className={styles.filter_btn} onClick={() => setFilter("back")}>Back-end</button>
                </div>
                <div className={styles.projects_container}>
                    {data.map(project => {
                        return (
                            <Project
                                key={project.id}
                                img={project.img}
                                name={project.name}
                                description={project.description}
                                stack={project.stack}
                                url={project.url}
                                show={project.type === filter}
                                alt={project.alt}
                            />
                        )
                    })}
                </div>
            </section>
        </>
    )
}