import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/projects.module.scss'

export default function Projects() {
    <>
        <Head>
            <title>Francis - Projects</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <section>

        </section>
    </>
}